// Generated by tools/gen_vbios_structs.py from tinygrad's `nv` autogen, itself generated from NVIDIA's
// open-gpu-kernel-modules. Do not edit: regenerate instead.
//
// The VBIOS structures the Ampere falcon boot walks. NVIDIA declares these inside .c files rather than headers, so
// unlike nv_structs.h these cannot be asserted against an included header - the assertions are generated with them.
//
// EVERY ONE OF THESE IS PACKED. The layouts are not naturally aligned and several fields straddle: BIT_HEADER's
// 32-bit Signature sits at offset 2, and a ucode table entry's 32-bit DescPtr sits at offset 2. Without the packed
// attribute the compiler would insert padding, every offset past the first hole would be wrong, and the generated
// assertions below are what would catch it.
#ifndef TINYNV_VBIOS_STRUCTS_H
#define TINYNV_VBIOS_STRUCTS_H
#include <stdint.h>
#include <stddef.h>

// BIT_HEADER_V1_00
typedef struct __attribute__((packed)) {
  uint16_t Id;
  uint32_t Signature;
  uint16_t BCD_Version;
  uint8_t HeaderSize;
  uint8_t TokenSize;
  uint8_t TokenEntries;
  uint8_t HeaderChksum;
} tinynv_bit_header_t;
_Static_assert(sizeof(tinynv_bit_header_t) == 12, "tinynv_bit_header_t is not 12 bytes");
_Static_assert(offsetof(tinynv_bit_header_t, Id) == 0, "tinynv_bit_header_t.Id moved");
_Static_assert(offsetof(tinynv_bit_header_t, Signature) == 2, "tinynv_bit_header_t.Signature moved");
_Static_assert(offsetof(tinynv_bit_header_t, BCD_Version) == 6, "tinynv_bit_header_t.BCD_Version moved");
_Static_assert(offsetof(tinynv_bit_header_t, HeaderSize) == 8, "tinynv_bit_header_t.HeaderSize moved");
_Static_assert(offsetof(tinynv_bit_header_t, TokenSize) == 9, "tinynv_bit_header_t.TokenSize moved");
_Static_assert(offsetof(tinynv_bit_header_t, TokenEntries) == 10, "tinynv_bit_header_t.TokenEntries moved");
_Static_assert(offsetof(tinynv_bit_header_t, HeaderChksum) == 11, "tinynv_bit_header_t.HeaderChksum moved");

// BIT_TOKEN_V1_00
typedef struct __attribute__((packed)) {
  uint8_t TokenId;
  uint8_t DataVersion;
  uint16_t DataSize;
  uint32_t DataPtr;
} tinynv_bit_token_t;
_Static_assert(sizeof(tinynv_bit_token_t) == 8, "tinynv_bit_token_t is not 8 bytes");
_Static_assert(offsetof(tinynv_bit_token_t, TokenId) == 0, "tinynv_bit_token_t.TokenId moved");
_Static_assert(offsetof(tinynv_bit_token_t, DataVersion) == 1, "tinynv_bit_token_t.DataVersion moved");
_Static_assert(offsetof(tinynv_bit_token_t, DataSize) == 2, "tinynv_bit_token_t.DataSize moved");
_Static_assert(offsetof(tinynv_bit_token_t, DataPtr) == 4, "tinynv_bit_token_t.DataPtr moved");

// BIT_DATA_FALCON_DATA_V2
typedef struct __attribute__((packed)) {
  uint32_t FalconUcodeTablePtr;
} tinynv_bit_falcon_data_t;
_Static_assert(sizeof(tinynv_bit_falcon_data_t) == 4, "tinynv_bit_falcon_data_t is not 4 bytes");
_Static_assert(offsetof(tinynv_bit_falcon_data_t, FalconUcodeTablePtr) == 0, "tinynv_bit_falcon_data_t.FalconUcodeTablePtr moved");

// FALCON_UCODE_TABLE_HDR_V1
typedef struct __attribute__((packed)) {
  uint8_t Version;
  uint8_t HeaderSize;
  uint8_t EntrySize;
  uint8_t EntryCount;
  uint8_t DescVersion;
  uint8_t DescSize;
} tinynv_falcon_ucode_table_hdr_t;
_Static_assert(sizeof(tinynv_falcon_ucode_table_hdr_t) == 6, "tinynv_falcon_ucode_table_hdr_t is not 6 bytes");
_Static_assert(offsetof(tinynv_falcon_ucode_table_hdr_t, Version) == 0, "tinynv_falcon_ucode_table_hdr_t.Version moved");
_Static_assert(offsetof(tinynv_falcon_ucode_table_hdr_t, HeaderSize) == 1, "tinynv_falcon_ucode_table_hdr_t.HeaderSize moved");
_Static_assert(offsetof(tinynv_falcon_ucode_table_hdr_t, EntrySize) == 2, "tinynv_falcon_ucode_table_hdr_t.EntrySize moved");
_Static_assert(offsetof(tinynv_falcon_ucode_table_hdr_t, EntryCount) == 3, "tinynv_falcon_ucode_table_hdr_t.EntryCount moved");
_Static_assert(offsetof(tinynv_falcon_ucode_table_hdr_t, DescVersion) == 4, "tinynv_falcon_ucode_table_hdr_t.DescVersion moved");
_Static_assert(offsetof(tinynv_falcon_ucode_table_hdr_t, DescSize) == 5, "tinynv_falcon_ucode_table_hdr_t.DescSize moved");

// FALCON_UCODE_TABLE_ENTRY_V1
typedef struct __attribute__((packed)) {
  uint8_t ApplicationID;
  uint8_t TargetID;
  uint32_t DescPtr;
} tinynv_falcon_ucode_table_entry_t;
_Static_assert(sizeof(tinynv_falcon_ucode_table_entry_t) == 6, "tinynv_falcon_ucode_table_entry_t is not 6 bytes");
_Static_assert(offsetof(tinynv_falcon_ucode_table_entry_t, ApplicationID) == 0, "tinynv_falcon_ucode_table_entry_t.ApplicationID moved");
_Static_assert(offsetof(tinynv_falcon_ucode_table_entry_t, TargetID) == 1, "tinynv_falcon_ucode_table_entry_t.TargetID moved");
_Static_assert(offsetof(tinynv_falcon_ucode_table_entry_t, DescPtr) == 2, "tinynv_falcon_ucode_table_entry_t.DescPtr moved");

// FALCON_UCODE_DESC_HEADER
typedef struct __attribute__((packed)) {
  uint32_t vDesc;
} tinynv_falcon_ucode_desc_hdr_t;
_Static_assert(sizeof(tinynv_falcon_ucode_desc_hdr_t) == 4, "tinynv_falcon_ucode_desc_hdr_t is not 4 bytes");
_Static_assert(offsetof(tinynv_falcon_ucode_desc_hdr_t, vDesc) == 0, "tinynv_falcon_ucode_desc_hdr_t.vDesc moved");

// FALCON_UCODE_DESC_V3
typedef struct __attribute__((packed)) {
  tinynv_falcon_ucode_desc_hdr_t Hdr;
  uint32_t StoredSize;
  uint32_t PKCDataOffset;
  uint32_t InterfaceOffset;
  uint32_t IMEMPhysBase;
  uint32_t IMEMLoadSize;
  uint32_t IMEMVirtBase;
  uint32_t DMEMPhysBase;
  uint32_t DMEMLoadSize;
  uint16_t EngineIdMask;
  uint8_t UcodeId;
  uint8_t SignatureCount;
  uint16_t SignatureVersions;
  uint16_t Reserved;
} tinynv_falcon_ucode_desc_v3_t;
_Static_assert(sizeof(tinynv_falcon_ucode_desc_v3_t) == 44, "tinynv_falcon_ucode_desc_v3_t is not 44 bytes");
_Static_assert(offsetof(tinynv_falcon_ucode_desc_v3_t, Hdr) == 0, "tinynv_falcon_ucode_desc_v3_t.Hdr moved");
_Static_assert(offsetof(tinynv_falcon_ucode_desc_v3_t, StoredSize) == 4, "tinynv_falcon_ucode_desc_v3_t.StoredSize moved");
_Static_assert(offsetof(tinynv_falcon_ucode_desc_v3_t, PKCDataOffset) == 8, "tinynv_falcon_ucode_desc_v3_t.PKCDataOffset moved");
_Static_assert(offsetof(tinynv_falcon_ucode_desc_v3_t, InterfaceOffset) == 12, "tinynv_falcon_ucode_desc_v3_t.InterfaceOffset moved");
_Static_assert(offsetof(tinynv_falcon_ucode_desc_v3_t, IMEMPhysBase) == 16, "tinynv_falcon_ucode_desc_v3_t.IMEMPhysBase moved");
_Static_assert(offsetof(tinynv_falcon_ucode_desc_v3_t, IMEMLoadSize) == 20, "tinynv_falcon_ucode_desc_v3_t.IMEMLoadSize moved");
_Static_assert(offsetof(tinynv_falcon_ucode_desc_v3_t, IMEMVirtBase) == 24, "tinynv_falcon_ucode_desc_v3_t.IMEMVirtBase moved");
_Static_assert(offsetof(tinynv_falcon_ucode_desc_v3_t, DMEMPhysBase) == 28, "tinynv_falcon_ucode_desc_v3_t.DMEMPhysBase moved");
_Static_assert(offsetof(tinynv_falcon_ucode_desc_v3_t, DMEMLoadSize) == 32, "tinynv_falcon_ucode_desc_v3_t.DMEMLoadSize moved");
_Static_assert(offsetof(tinynv_falcon_ucode_desc_v3_t, EngineIdMask) == 36, "tinynv_falcon_ucode_desc_v3_t.EngineIdMask moved");
_Static_assert(offsetof(tinynv_falcon_ucode_desc_v3_t, UcodeId) == 38, "tinynv_falcon_ucode_desc_v3_t.UcodeId moved");
_Static_assert(offsetof(tinynv_falcon_ucode_desc_v3_t, SignatureCount) == 39, "tinynv_falcon_ucode_desc_v3_t.SignatureCount moved");
_Static_assert(offsetof(tinynv_falcon_ucode_desc_v3_t, SignatureVersions) == 40, "tinynv_falcon_ucode_desc_v3_t.SignatureVersions moved");
_Static_assert(offsetof(tinynv_falcon_ucode_desc_v3_t, Reserved) == 42, "tinynv_falcon_ucode_desc_v3_t.Reserved moved");

// FALCON_APPLICATION_INTERFACE_HEADER_V1
typedef struct __attribute__((packed)) {
  uint8_t version;
  uint8_t headerSize;
  uint8_t entrySize;
  uint8_t entryCount;
} tinynv_falcon_app_if_hdr_t;
_Static_assert(sizeof(tinynv_falcon_app_if_hdr_t) == 4, "tinynv_falcon_app_if_hdr_t is not 4 bytes");
_Static_assert(offsetof(tinynv_falcon_app_if_hdr_t, version) == 0, "tinynv_falcon_app_if_hdr_t.version moved");
_Static_assert(offsetof(tinynv_falcon_app_if_hdr_t, headerSize) == 1, "tinynv_falcon_app_if_hdr_t.headerSize moved");
_Static_assert(offsetof(tinynv_falcon_app_if_hdr_t, entrySize) == 2, "tinynv_falcon_app_if_hdr_t.entrySize moved");
_Static_assert(offsetof(tinynv_falcon_app_if_hdr_t, entryCount) == 3, "tinynv_falcon_app_if_hdr_t.entryCount moved");

// FALCON_APPLICATION_INTERFACE_ENTRY_V1
typedef struct __attribute__((packed)) {
  uint32_t id;
  uint32_t dmemOffset;
} tinynv_falcon_app_if_entry_t;
_Static_assert(sizeof(tinynv_falcon_app_if_entry_t) == 8, "tinynv_falcon_app_if_entry_t is not 8 bytes");
_Static_assert(offsetof(tinynv_falcon_app_if_entry_t, id) == 0, "tinynv_falcon_app_if_entry_t.id moved");
_Static_assert(offsetof(tinynv_falcon_app_if_entry_t, dmemOffset) == 4, "tinynv_falcon_app_if_entry_t.dmemOffset moved");

// FALCON_APPLICATION_INTERFACE_DMEM_MAPPER_V3
typedef struct __attribute__((packed)) {
  uint32_t signature;
  uint16_t version;
  uint16_t size;
  uint32_t cmd_in_buffer_offset;
  uint32_t cmd_in_buffer_size;
  uint32_t cmd_out_buffer_offset;
  uint32_t cmd_out_buffer_size;
  uint32_t nvf_img_data_buffer_offset;
  uint32_t nvf_img_data_buffer_size;
  uint32_t printfBufferHdr;
  uint32_t ucode_build_time_stamp;
  uint32_t ucode_signature;
  uint32_t init_cmd;
  uint32_t ucode_feature;
  uint32_t ucode_cmd_mask0;
  uint32_t ucode_cmd_mask1;
  uint32_t multiTgtTbl;
} tinynv_falcon_dmem_mapper_t;
_Static_assert(sizeof(tinynv_falcon_dmem_mapper_t) == 64, "tinynv_falcon_dmem_mapper_t is not 64 bytes");
_Static_assert(offsetof(tinynv_falcon_dmem_mapper_t, signature) == 0, "tinynv_falcon_dmem_mapper_t.signature moved");
_Static_assert(offsetof(tinynv_falcon_dmem_mapper_t, version) == 4, "tinynv_falcon_dmem_mapper_t.version moved");
_Static_assert(offsetof(tinynv_falcon_dmem_mapper_t, size) == 6, "tinynv_falcon_dmem_mapper_t.size moved");
_Static_assert(offsetof(tinynv_falcon_dmem_mapper_t, cmd_in_buffer_offset) == 8, "tinynv_falcon_dmem_mapper_t.cmd_in_buffer_offset moved");
_Static_assert(offsetof(tinynv_falcon_dmem_mapper_t, cmd_in_buffer_size) == 12, "tinynv_falcon_dmem_mapper_t.cmd_in_buffer_size moved");
_Static_assert(offsetof(tinynv_falcon_dmem_mapper_t, cmd_out_buffer_offset) == 16, "tinynv_falcon_dmem_mapper_t.cmd_out_buffer_offset moved");
_Static_assert(offsetof(tinynv_falcon_dmem_mapper_t, cmd_out_buffer_size) == 20, "tinynv_falcon_dmem_mapper_t.cmd_out_buffer_size moved");
_Static_assert(offsetof(tinynv_falcon_dmem_mapper_t, nvf_img_data_buffer_offset) == 24, "tinynv_falcon_dmem_mapper_t.nvf_img_data_buffer_offset moved");
_Static_assert(offsetof(tinynv_falcon_dmem_mapper_t, nvf_img_data_buffer_size) == 28, "tinynv_falcon_dmem_mapper_t.nvf_img_data_buffer_size moved");
_Static_assert(offsetof(tinynv_falcon_dmem_mapper_t, printfBufferHdr) == 32, "tinynv_falcon_dmem_mapper_t.printfBufferHdr moved");
_Static_assert(offsetof(tinynv_falcon_dmem_mapper_t, ucode_build_time_stamp) == 36, "tinynv_falcon_dmem_mapper_t.ucode_build_time_stamp moved");
_Static_assert(offsetof(tinynv_falcon_dmem_mapper_t, ucode_signature) == 40, "tinynv_falcon_dmem_mapper_t.ucode_signature moved");
_Static_assert(offsetof(tinynv_falcon_dmem_mapper_t, init_cmd) == 44, "tinynv_falcon_dmem_mapper_t.init_cmd moved");
_Static_assert(offsetof(tinynv_falcon_dmem_mapper_t, ucode_feature) == 48, "tinynv_falcon_dmem_mapper_t.ucode_feature moved");
_Static_assert(offsetof(tinynv_falcon_dmem_mapper_t, ucode_cmd_mask0) == 52, "tinynv_falcon_dmem_mapper_t.ucode_cmd_mask0 moved");
_Static_assert(offsetof(tinynv_falcon_dmem_mapper_t, ucode_cmd_mask1) == 56, "tinynv_falcon_dmem_mapper_t.ucode_cmd_mask1 moved");
_Static_assert(offsetof(tinynv_falcon_dmem_mapper_t, multiTgtTbl) == 60, "tinynv_falcon_dmem_mapper_t.multiTgtTbl moved");

// FWSECLIC_READ_VBIOS_DESC
typedef struct __attribute__((packed)) {
  uint32_t version;
  uint32_t size;
  uint64_t gfwImageOffset;
  uint32_t gfwImageSize;
  uint32_t flags;
} tinynv_fwsec_read_vbios_desc_t;
_Static_assert(sizeof(tinynv_fwsec_read_vbios_desc_t) == 24, "tinynv_fwsec_read_vbios_desc_t is not 24 bytes");
_Static_assert(offsetof(tinynv_fwsec_read_vbios_desc_t, version) == 0, "tinynv_fwsec_read_vbios_desc_t.version moved");
_Static_assert(offsetof(tinynv_fwsec_read_vbios_desc_t, size) == 4, "tinynv_fwsec_read_vbios_desc_t.size moved");
_Static_assert(offsetof(tinynv_fwsec_read_vbios_desc_t, gfwImageOffset) == 8, "tinynv_fwsec_read_vbios_desc_t.gfwImageOffset moved");
_Static_assert(offsetof(tinynv_fwsec_read_vbios_desc_t, gfwImageSize) == 16, "tinynv_fwsec_read_vbios_desc_t.gfwImageSize moved");
_Static_assert(offsetof(tinynv_fwsec_read_vbios_desc_t, flags) == 20, "tinynv_fwsec_read_vbios_desc_t.flags moved");

// FWSECLIC_FRTS_REGION_DESC
typedef struct __attribute__((packed)) {
  uint32_t version;
  uint32_t size;
  uint32_t frtsRegionOffset4K;
  uint32_t frtsRegionSize;
  uint32_t frtsRegionMediaType;
} tinynv_fwsec_frts_region_desc_t;
_Static_assert(sizeof(tinynv_fwsec_frts_region_desc_t) == 20, "tinynv_fwsec_frts_region_desc_t is not 20 bytes");
_Static_assert(offsetof(tinynv_fwsec_frts_region_desc_t, version) == 0, "tinynv_fwsec_frts_region_desc_t.version moved");
_Static_assert(offsetof(tinynv_fwsec_frts_region_desc_t, size) == 4, "tinynv_fwsec_frts_region_desc_t.size moved");
_Static_assert(offsetof(tinynv_fwsec_frts_region_desc_t, frtsRegionOffset4K) == 8, "tinynv_fwsec_frts_region_desc_t.frtsRegionOffset4K moved");
_Static_assert(offsetof(tinynv_fwsec_frts_region_desc_t, frtsRegionSize) == 12, "tinynv_fwsec_frts_region_desc_t.frtsRegionSize moved");
_Static_assert(offsetof(tinynv_fwsec_frts_region_desc_t, frtsRegionMediaType) == 16, "tinynv_fwsec_frts_region_desc_t.frtsRegionMediaType moved");

// FWSECLIC_FRTS_CMD
typedef struct __attribute__((packed)) {
  tinynv_fwsec_read_vbios_desc_t readVbiosDesc;
  tinynv_fwsec_frts_region_desc_t frtsRegionDesc;
} tinynv_fwsec_frts_cmd_t;
_Static_assert(sizeof(tinynv_fwsec_frts_cmd_t) == 44, "tinynv_fwsec_frts_cmd_t is not 44 bytes");
_Static_assert(offsetof(tinynv_fwsec_frts_cmd_t, readVbiosDesc) == 0, "tinynv_fwsec_frts_cmd_t.readVbiosDesc moved");
_Static_assert(offsetof(tinynv_fwsec_frts_cmd_t, frtsRegionDesc) == 24, "tinynv_fwsec_frts_cmd_t.frtsRegionDesc moved");

// struct_nvfw_hs_header_v2
typedef struct __attribute__((packed)) {
  uint32_t sig_prod_offset;
  uint32_t sig_prod_size;
  uint32_t patch_loc;
  uint32_t patch_sig;
  uint32_t meta_data_offset;
  uint32_t meta_data_size;
  uint32_t num_sig;
  uint32_t header_offset;
  uint32_t header_size;
} tinynv_nvfw_hs_header_v2_t;
_Static_assert(sizeof(tinynv_nvfw_hs_header_v2_t) == 36, "tinynv_nvfw_hs_header_v2_t is not 36 bytes");
_Static_assert(offsetof(tinynv_nvfw_hs_header_v2_t, sig_prod_offset) == 0, "tinynv_nvfw_hs_header_v2_t.sig_prod_offset moved");
_Static_assert(offsetof(tinynv_nvfw_hs_header_v2_t, sig_prod_size) == 4, "tinynv_nvfw_hs_header_v2_t.sig_prod_size moved");
_Static_assert(offsetof(tinynv_nvfw_hs_header_v2_t, patch_loc) == 8, "tinynv_nvfw_hs_header_v2_t.patch_loc moved");
_Static_assert(offsetof(tinynv_nvfw_hs_header_v2_t, patch_sig) == 12, "tinynv_nvfw_hs_header_v2_t.patch_sig moved");
_Static_assert(offsetof(tinynv_nvfw_hs_header_v2_t, meta_data_offset) == 16, "tinynv_nvfw_hs_header_v2_t.meta_data_offset moved");
_Static_assert(offsetof(tinynv_nvfw_hs_header_v2_t, meta_data_size) == 20, "tinynv_nvfw_hs_header_v2_t.meta_data_size moved");
_Static_assert(offsetof(tinynv_nvfw_hs_header_v2_t, num_sig) == 24, "tinynv_nvfw_hs_header_v2_t.num_sig moved");
_Static_assert(offsetof(tinynv_nvfw_hs_header_v2_t, header_offset) == 28, "tinynv_nvfw_hs_header_v2_t.header_offset moved");
_Static_assert(offsetof(tinynv_nvfw_hs_header_v2_t, header_size) == 32, "tinynv_nvfw_hs_header_v2_t.header_size moved");

// struct_nvfw_hs_load_header_v2
typedef struct __attribute__((packed)) {
  uint32_t os_code_offset;
  uint32_t os_code_size;
  uint32_t os_data_offset;
  uint32_t os_data_size;
  uint32_t num_apps;
  // app[] follows at offset 20; read as tinynv_nvfw_hs_load_header_app_t
} tinynv_nvfw_hs_load_header_v2_t;
_Static_assert(sizeof(tinynv_nvfw_hs_load_header_v2_t) == 20, "tinynv_nvfw_hs_load_header_v2_t is not 20 bytes");
_Static_assert(offsetof(tinynv_nvfw_hs_load_header_v2_t, os_code_offset) == 0, "tinynv_nvfw_hs_load_header_v2_t.os_code_offset moved");
_Static_assert(offsetof(tinynv_nvfw_hs_load_header_v2_t, os_code_size) == 4, "tinynv_nvfw_hs_load_header_v2_t.os_code_size moved");
_Static_assert(offsetof(tinynv_nvfw_hs_load_header_v2_t, os_data_offset) == 8, "tinynv_nvfw_hs_load_header_v2_t.os_data_offset moved");
_Static_assert(offsetof(tinynv_nvfw_hs_load_header_v2_t, os_data_size) == 12, "tinynv_nvfw_hs_load_header_v2_t.os_data_size moved");
_Static_assert(offsetof(tinynv_nvfw_hs_load_header_v2_t, num_apps) == 16, "tinynv_nvfw_hs_load_header_v2_t.num_apps moved");

// struct_nvfw_hs_load_header_v2_app
typedef struct __attribute__((packed)) {
  uint32_t offset;
  uint32_t size;
  uint32_t data_offset;
  uint32_t data_size;
} tinynv_nvfw_hs_load_header_app_t;
_Static_assert(sizeof(tinynv_nvfw_hs_load_header_app_t) == 16, "tinynv_nvfw_hs_load_header_app_t is not 16 bytes");
_Static_assert(offsetof(tinynv_nvfw_hs_load_header_app_t, offset) == 0, "tinynv_nvfw_hs_load_header_app_t.offset moved");
_Static_assert(offsetof(tinynv_nvfw_hs_load_header_app_t, size) == 4, "tinynv_nvfw_hs_load_header_app_t.size moved");
_Static_assert(offsetof(tinynv_nvfw_hs_load_header_app_t, data_offset) == 8, "tinynv_nvfw_hs_load_header_app_t.data_offset moved");
_Static_assert(offsetof(tinynv_nvfw_hs_load_header_app_t, data_size) == 12, "tinynv_nvfw_hs_load_header_app_t.data_size moved");

// the named values the walk compares against
#define TINYNV_PCI_ROM_IMAGE_BLOCK_SIZE 0x200
#define TINYNV_OFFSETOF_PCI_EXP_ROM_PCI_DATA_STRUCT_PTR 0x18
#define TINYNV_OFFSETOF_PCI_DATA_STRUCT_IMAGE_LEN 0x10
#define TINYNV_OFFSETOF_PCI_DATA_STRUCT_CODE_TYPE 0x14
#define TINYNV_NV_BCRT_HASH_INFO_BASE_CODE_TYPE_VBIOS_BASE 0x0
#define TINYNV_NV_BCRT_HASH_INFO_BASE_CODE_TYPE_VBIOS_EXT 0xe0
#define TINYNV_BIT_TOKEN_FALCON_DATA 0x70
#define TINYNV_BIT_DATA_FALCON_DATA_V2_SIZE_4 0x4
#define TINYNV_FALCON_UCODE_ENTRY_APPID_FWSEC_PROD 0x85
#define TINYNV_FALCON_UCODE_DESC_V3_SIZE_44 0x2c
#define TINYNV_FALCON_APPLICATION_INTERFACE_ENTRY_ID_DMEMMAPPER 0x4

#endif
