#!/usr/bin/env python3
"""Emit the C structures the Ampere falcon boot reads out of the card's own VBIOS.

These are NOT in the pinned kernel-module tree's headers. NVIDIA declares them inside .c files - FWSECLIC_FRTS_CMD and
the DMEM mapper in kernel_gsp_frts_tu102.c, the ucode table and descriptor in kernel_gsp_fwsec.c - so the trick
test_headers.c uses for everything else (include the real header, _Static_assert against it) is not available: there is
no header to include. The choice is to type them in by hand or to generate them, and a structure typed in by hand is
exactly what this driver does not do, because a field at the wrong offset here does not fail cleanly. It hands the boot
ROM a signature at the wrong place and the card refuses to run the image without saying why.

So they come from tinygrad's `nv` autogen, which is generated from that same tree, and every size and every offset is
baked into a _Static_assert next to the declaration. Regenerating after a tinygrad bump either produces the same file or
breaks the build.

    python tools/gen_vbios_structs.py cuda-shim/libtinynv/src/vbios_structs.h
"""
from __future__ import annotations
import ctypes, sys, pathlib

# (autogen name, our name) - the ones the boot path actually reads, in the order it reads them
STRUCTS = [
  ("BIT_HEADER_V1_00",                            "tinynv_bit_header_t"),
  ("BIT_TOKEN_V1_00",                             "tinynv_bit_token_t"),
  ("BIT_DATA_FALCON_DATA_V2",                     "tinynv_bit_falcon_data_t"),
  ("FALCON_UCODE_TABLE_HDR_V1",                   "tinynv_falcon_ucode_table_hdr_t"),
  ("FALCON_UCODE_TABLE_ENTRY_V1",                 "tinynv_falcon_ucode_table_entry_t"),
  ("FALCON_UCODE_DESC_HEADER",                    "tinynv_falcon_ucode_desc_hdr_t"),
  ("FALCON_UCODE_DESC_V3",                        "tinynv_falcon_ucode_desc_v3_t"),
  ("FALCON_APPLICATION_INTERFACE_HEADER_V1",      "tinynv_falcon_app_if_hdr_t"),
  ("FALCON_APPLICATION_INTERFACE_ENTRY_V1",       "tinynv_falcon_app_if_entry_t"),
  ("FALCON_APPLICATION_INTERFACE_DMEM_MAPPER_V3", "tinynv_falcon_dmem_mapper_t"),
  ("FWSECLIC_READ_VBIOS_DESC",                    "tinynv_fwsec_read_vbios_desc_t"),
  ("FWSECLIC_FRTS_REGION_DESC",                   "tinynv_fwsec_frts_region_desc_t"),
  ("FWSECLIC_FRTS_CMD",                           "tinynv_fwsec_frts_cmd_t"),
  # struct_nvfw_bin_hdr is NOT here: nv_structs.h already declares tinynv_nvfw_bin_hdr_t for the Blackwell bootloader
  # and asserts it against the real header, which is the better source. Declaring it again here would be a second
  # definition of the same 24 bytes that could drift from the first.
  ("struct_nvfw_hs_header_v2",                    "tinynv_nvfw_hs_header_v2_t"),
  ("struct_nvfw_hs_load_header_v2",               "tinynv_nvfw_hs_load_header_v2_t"),
  ("struct_nvfw_hs_load_header_v2_app",           "tinynv_nvfw_hs_load_header_app_t"),
]

CONSTS = [
  # walking the PCI expansion ROM chain to find where the extended image starts
  "PCI_ROM_IMAGE_BLOCK_SIZE", "OFFSETOF_PCI_EXP_ROM_PCI_DATA_STRUCT_PTR",
  "OFFSETOF_PCI_DATA_STRUCT_IMAGE_LEN", "OFFSETOF_PCI_DATA_STRUCT_CODE_TYPE",
  "NV_BCRT_HASH_INFO_BASE_CODE_TYPE_VBIOS_BASE", "NV_BCRT_HASH_INFO_BASE_CODE_TYPE_VBIOS_EXT",
  # finding FWSEC in the BIT table, and the one descriptor size the driver understands
  "BIT_TOKEN_FALCON_DATA", "BIT_DATA_FALCON_DATA_V2_SIZE_4",
  "FALCON_UCODE_ENTRY_APPID_FWSEC_PROD", "FALCON_UCODE_DESC_V3_SIZE_44",
  "FALCON_APPLICATION_INTERFACE_ENTRY_ID_DMEMMAPPER",
]

HEAD = """// Generated by tools/gen_vbios_structs.py from tinygrad's `nv` autogen, itself generated from NVIDIA's
// open-gpu-kernel-modules. Do not edit: regenerate instead.
//
// The VBIOS structures the Ampere falcon boot walks. NVIDIA declares these inside .c files rather than headers, so
// unlike nv_structs.h these cannot be asserted against an included header - the assertions are generated with them.
//
// EVERY ONE OF THESE IS PACKED. The layouts are not naturally aligned and several fields straddle: BIT_HEADER's
// 32-bit Signature sits at offset 2, and a ucode table entry's 32-bit DescPtr sits at offset 2. Without the packed
// attribute the compiler would insert padding, every offset past the first hole would be wrong, and the generated
// assertions below are what would catch it.
#ifndef TINYNV_VBIOS_STRUCTS_H
#define TINYNV_VBIOS_STRUCTS_H
#include <stdint.h>
#include <stddef.h>
"""

def ctype_name(t, sizeof_to_name):
  if hasattr(t, "_real_fields_"): return None  # a nested structure: resolved by the caller
  n = sizeof_to_name.get(ctypes.sizeof(t))
  if n is None: raise SystemExit(f"no C type for {t} of {ctypes.sizeof(t)} bytes")
  return n

def main(out_path: str):
  sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1] / "tinygrad"))
  from tinygrad.runtime.autogen import nv

  by_autogen = {a: c for a, c in STRUCTS}
  ints = {1: "uint8_t", 2: "uint16_t", 4: "uint32_t", 8: "uint64_t"}
  lines = []
  for autogen_name, our_name in STRUCTS:
    t = getattr(nv, autogen_name, None)
    if t is None: raise SystemExit(f"{autogen_name} is not in tinygrad's nv autogen: upstream renamed it")
    size = ctypes.sizeof(t)
    lines.append(f"// {autogen_name}")
    lines.append("typedef struct __attribute__((packed)) {")
    asserts, prev_end = [], 0
    for fname, ftype, foff in t._real_fields_:
      if isinstance(ftype, type) and issubclass(ftype, ctypes.Array):
        # a zero-length trailing array: the real entries follow the structure and are read separately
        lines.append(f"  // {fname}[] follows at offset {foff}; read as {by_autogen.get(ftype._type_.__name__, ftype._type_.__name__)}")
        continue
      if foff > prev_end: lines.append(f"  uint8_t _pad{prev_end}[{foff - prev_end}];")
      if hasattr(ftype, "_real_fields_"):
        nested = by_autogen.get(ftype.__name__)
        if nested is None: raise SystemExit(f"{autogen_name}.{fname} is a {ftype.__name__}, which is not generated")
        lines.append(f"  {nested} {fname};")
      else:
        lines.append(f"  {ctype_name(ftype, ints)} {fname};")
      asserts.append((fname, foff))
      prev_end = foff + ctypes.sizeof(ftype)
    if size > prev_end: lines.append(f"  uint8_t _pad{prev_end}[{size - prev_end}];")
    lines.append(f"}} {our_name};")
    lines.append(f'_Static_assert(sizeof({our_name}) == {size}, "{our_name} is not {size} bytes");')
    for fname, foff in asserts:
      lines.append(f'_Static_assert(offsetof({our_name}, {fname}) == {foff}, "{our_name}.{fname} moved");')
    lines.append("")

  lines.append("// the named values the walk compares against")
  for c in CONSTS:
    v = getattr(nv, c, None)
    if v is None: raise SystemExit(f"{c} is not in tinygrad's nv autogen: upstream renamed it")
    lines.append(f"#define TINYNV_{c} {int(v):#x}")
  lines.append("")

  pathlib.Path(out_path).write_text(HEAD + "\n" + "\n".join(lines) + "\n#endif\n")
  print(f"wrote {out_path}: {len(STRUCTS)} structures and {len(CONSTS)} constants from tinygrad's nv autogen")

if __name__ == "__main__":
  main(sys.argv[1] if len(sys.argv) > 1 else "cuda-shim/libtinynv/src/vbios_structs.h")
