#!/usr/bin/env python3
"""Emit the loadable image the oracle builds for a cubin, so the C loader can be compared against it.

A cubin is not a loadable thing: the code, each constant bank and any __device__ data are separate sections that have to
be laid out into one block, because every address the GPU is given is an offset into that block. Getting the layout wrong
does not fail to load - it launches a kernel whose constant bank points somewhere else.

This runs tinygrad's own `elf_loader` with the same section alignment the NV path uses, and writes down the image it
produced, the addresses it assigned, and every relocation it resolved. The C side builds its own and is compared against
this: the bytes by hash, the addresses and the relocations one by one.

One deliberate difference, stated here rather than discovered as a mismatch. The oracle picks constant bank 0 by matching
`.nv.constant\\d+` against every section, so in a cubin holding several kernels it ends up with whichever `.nv.constant0.*`
it met last. That is right for tinygrad, which compiles one kernel per cubin, and wrong for a ggml cubin holding hundreds.
So the reference reads bank 0 for the named kernel and the C loader does the same; the relocations and the layout, which
is what elf_loader actually decides, are compared against the oracle exactly.

    python tools/nv_reference_image.py ../spike/norm.cubin test/reference-image.txt [kernel ...]
"""
from __future__ import annotations
import os
import hashlib, pathlib, re, sys

sys.path.insert(0, os.environ.get("TINYGRAD_SRC", os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "..", "tinygrad")))
from tinygrad.runtime.support.elf import elf_loader  # noqa: E402

def main(cubin_path: str, out_path: str, wanted: list[str]) -> int:
  lib = pathlib.Path(cubin_path).read_bytes()
  image, sections, relocs = elf_loader(lib, force_section_align=128)
  image = bytes(image)

  kernels = [s.name[len(".text."):] for s in sections if s.name.startswith(".text.") and s.header.sh_type == 1]
  if not wanted: wanted = kernels[:3] + kernels[-1:]     # a few from each end is enough to catch a layout that drifts
  for k in wanted:
    if k not in kernels: return err(f"{cubin_path} has no kernel {k}")

  lines = [f"# generated by tools/nv_reference_image.py from tinygrad's own elf_loader",
           f"# cubin {cubin_path}: {len(kernels)} kernels, {len(sections)} sections",
           f"image len={len(image)} sha256={hashlib.sha256(image).hexdigest()}",
           f"relocs n={len(relocs)}"]
  for at, target, typ, addend in relocs:
    lines.append(f"reloc at={at:#x} target={target:#x} type={typ:#x} addend={addend}")

  for k in wanted:
    text = next(s.header.sh_addr for s in sections if s.name == f".text.{k}")
    banks = []
    for s in sections:
      if s.header.sh_type != 1: continue
      if (m := re.fullmatch(r"\.nv\.constant(\d+)(?:\.(.*))?", s.name)) is None: continue
      bank, who = int(m.group(1)), m.group(2)
      if who is not None and who != k: continue
      if bank == 0 and who is None: continue
      banks.append(f"cbuf{bank}={s.header.sh_addr:#x}:{s.header.sh_size:#x}")
    lines.append(f"kernel name={k} text={text:#x} " + " ".join(sorted(banks)))

  pathlib.Path(out_path).write_text("\n".join(lines) + "\n")
  print(f"wrote {out_path}: {len(image)} byte image, {len(relocs)} relocations, {len(wanted)} of {len(kernels)} kernels")
  return 0

def err(msg: str) -> int:
  print(f"  {msg}")
  return 1

if __name__ == "__main__":
  if len(sys.argv) < 3: raise SystemExit("usage: nv_reference_image.py <cubin> <out> [kernel ...]")
  raise SystemExit(main(sys.argv[1], sys.argv[2], sys.argv[3:]))
