// Checks the command-buffer encoder against what the oracle builds, word for word.
//
// The recorded session could not supply these bytes: the command buffer lives in host memory the client maps directly,
// so its contents crossed neither recorder. What the recording does supply is each buffer's length, carried in the ring
// entry, and that is what keeps this comparison honest. A reference build free to choose its own length could agree with
// this encoder perfectly and both could be wrong; pinned to 22 and 16 dwords, the lengths the card was actually handed,
// they cannot be.
//
// The reference is generated by tools/nv_reference_submit.py from the oracle's own method numbers and flag fields, with
// placeholder addresses chosen so a swapped high and low word shows up as a mismatch rather than as a coincidence.
#include "submit.h"
#include "internal.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static int fails;
// Every CHECK counts itself, and the run asserts it executed at least as many as there are CHECK sites in this file -
// a number the Makefile greps out at build time, so it cannot go stale the way a literal would.
//
// The reason, from Session C: their guarantee-5 test reported PASSED while testing nothing. The branch that asked the
// question was never reached, it printed "(inconclusive)" and counted nothing, and the suite called that success. The
// rule they drew is "any branch that cannot reach a verdict is a failure", and the same hole is open in this file
// wherever checks sit inside a loop over recorded data: a recording that failed to parse would run the loop zero
// times and still print "all checks passed". A floor cannot catch every skipped case, but it catches a whole block
// going missing, which is the shape that actually happens.
static int checks;
#define CHECK(cond, ...) do { checks++; if (!(cond)) { printf("  FAIL: "); printf(__VA_ARGS__); printf("\n"); fails++; } } while (0)

// the same placeholders the generator uses
#define SEM_ADDR 0x1122334455667788ull
#define SEM_VALUE 0x99aabbccddeeff00ull
#define LOCAL_WINDOW 0x729300000000ull
#define SHARED_WINDOW 0x729400000000ull
#define COMPUTE_CLASS 0xcec0
#define COPY_CLASS 0xcab5
#define QMD_ADDR 0x7f1122330000ull

typedef struct { char name[32]; uint32_t n; uint32_t words[64]; } reference_t;

static int load_reference(const char *path, reference_t *out, int max) {
  FILE *f = fopen(path, "r");
  if (!f) { printf("  cannot open %s: run tools/nv_reference_submit.py\n", path); return -1; }
  char line[4096];
  int n = 0;
  while (n < max && fgets(line, sizeof(line), f)) {
    if (line[0] == '#' || line[0] == '\n') continue;
    char *save = NULL, *tok = strtok_r(line, " \t\n", &save);
    if (!tok) continue;
    snprintf(out[n].name, sizeof(out[n].name), "%s", tok);
    out[n].n = 0;
    if (!(tok = strtok_r(NULL, " \t\n", &save))) continue; // the dword count, re-derived below from what follows
    while ((tok = strtok_r(NULL, " \t\n", &save)) && out[n].n < 64) out[n].words[out[n].n++] = (uint32_t)strtoul(tok, NULL, 0);
    n++;
  }
  fclose(f);
  return n;
}

static void compare(const reference_t *want, const tinynv_cmdbuf_t *got) {
  if (got->n != want->n) {
    printf("  FAIL: %s is %u dwords, the oracle builds %u\n", want->name, got->n, want->n);
    fails++;
    return;
  }
  for (uint32_t i = 0; i < want->n; i++)
    if (got->words[i] != want->words[i]) {
      printf("  FAIL: %s word %u is %#010x, the oracle builds %#010x\n", want->name, i, got->words[i], want->words[i]);
      fails++;
      return; // the first difference is the one worth reading; the rest are usually its shadow
    }
  printf("  %-16s %2u dwords, identical to the oracle\n", want->name, got->n);
}

int main(int argc, char **argv) {
  const char *path = argc > 1 ? argv[1] : "test/reference-submit.txt";
  reference_t want[8];
  int n = load_reference(path, want, 8);
  if (n < 3) { printf("%s holds %d batches, expected 3\n", path, n); return 1; }

  uint32_t storage[64];
  tinynv_cmdbuf_t c = {.words = storage, .n = 0, .cap = 64};
  CHECK(!tinynv_cmd_compute_setup(&c, SEM_ADDR, SEM_VALUE, COMPUTE_CLASS, LOCAL_WINDOW, SHARED_WINDOW),
        "building the compute setup failed: %s", tinynv_last_error());
  compare(&want[0], &c);

  c.n = 0;
  CHECK(!tinynv_cmd_copy_setup(&c, SEM_ADDR, SEM_VALUE, COPY_CLASS), "building the copy setup failed: %s", tinynv_last_error());
  compare(&want[1], &c);

  c.n = 0;
  CHECK(!tinynv_cmd_launch(&c, QMD_ADDR), "building the launch failed: %s", tinynv_last_error());
  compare(&want[2], &c);

  // The copy engine's own release. This is the one the compute path's host methods cannot stand in for: a host-method
  // release on a copy channel can retire before the engine has drained, and what makes this one different is the
  // FLUSH_ENABLE bit that pushes the engine's writes out before the payload lands. Checked here because the difference
  // between the two encodings is four bits in one dword, and four bits is not something to get right by eye.
  c.n = 0;
  CHECK(!tinynv_cmd_copy_release(&c, SEM_ADDR, SEM_VALUE), "building the copy release failed: %s", tinynv_last_error());
  compare(&want[3], &c);

  // the ring entry, against the values the card was actually handed in traces/5090-wire
  struct { uint64_t va; uint32_t dwords; uint64_t entry; } recorded[] = {
    {0x1020018000ull, 22, 0x5a1020018000ull},
    {0x1020578000ull, 16, 0x421020578000ull},
    {0x1020188000ull, 32, 0x821020188000ull},
  };
  for (size_t i = 0; i < sizeof(recorded) / sizeof(*recorded); i++) {
    uint64_t got = tinynv_ring_entry(recorded[i].va, recorded[i].dwords);
    CHECK(got == recorded[i].entry, "ring entry for %#llx of %u dwords is %#llx, the card was handed %#llx",
          (unsigned long long)recorded[i].va, recorded[i].dwords, (unsigned long long)got,
          (unsigned long long)recorded[i].entry);
  }
  if (!fails) printf("  ring entries: 3 rebuilt exactly as recorded, address, length and flag\n");

  // and a buffer that will not fit must refuse rather than run off the end
  uint32_t tiny[4];
  tinynv_cmdbuf_t small = {.words = tiny, .n = 0, .cap = 4};
  CHECK(tinynv_cmd_compute_setup(&small, SEM_ADDR, SEM_VALUE, COMPUTE_CLASS, LOCAL_WINDOW, SHARED_WINDOW),
        "a batch larger than its buffer was encoded anyway");

  // The two timestamp methods, which differ in exactly one bit and are impossible to tell apart by reading the call
  // site. tinynv_cmd_release_ts always waits for the engine to drain - its `timestamp` argument only chooses whether a
  // clock is written - so it times the END of a batch wherever it is placed. tinynv_cmd_timestamp does not wait, which
  // is the only reason it can time a start. The refill instrument measured the wrong edge for a day because the first
  // was used where the second was meant, and nothing anywhere would have said so: both encode, both run, and the
  // number that comes out is plausible. So the bit is pinned here, against the field positions in NVIDIA's clc56f.h.
  {
    uint32_t words[16];
    tinynv_cmdbuf_t t = {.words = words, .n = 0, .cap = 16};
    CHECK(!tinynv_cmd_timestamp(&t, SEM_ADDR, SEM_VALUE), "building a start timestamp failed: %s", tinynv_last_error());
    CHECK(t.n == 6, "a semaphore method is 6 dwords, this one is %u - batch_begin reserves exactly 6 for it", t.n);
    uint32_t flags = words[5];
    CHECK(!(flags & (1u << 20)), "the start timestamp sets RELEASE_WFI, so it times when the batch FINISHED");
    CHECK(flags & (1u << 25), "the start timestamp does not ask for a timestamp, so there is no clock to read");

    tinynv_cmdbuf_t e = {.words = words, .n = 0, .cap = 16};
    CHECK(!tinynv_cmd_release_ts(&e, SEM_ADDR, SEM_VALUE, 1), "building an end timestamp failed: %s", tinynv_last_error());
    CHECK(words[5] & (1u << 20), "the end timestamp does NOT wait for idle, so it no longer means the work is done");
    CHECK(words[5] & (1u << 25), "the end timestamp does not ask for a timestamp");
    // And the head timestamp must not raise the interrupt that ends a batch: two batch-completion interrupts for one
    // batch is a second thing the engine reports and the driver does not expect.
    CHECK(t.n == 6, "the start timestamp appended an interrupt method as well");
    // And the batch-ending release that carries a clock. It must do everything tinynv_cmd_release does - wait for
    // idle, announce the batch with the interrupt - and differ only in leaving a timestamp behind. Getting the
    // interrupt wrong here is silent: the batch still completes, the host still wakes on the semaphore, and what
    // breaks is whatever else was listening.
    tinynv_cmdbuf_t k = {.words = words, .n = 0, .cap = 16};
    CHECK(!tinynv_cmd_release_clocked(&k, SEM_ADDR, SEM_VALUE), "building a clocked release failed: %s",
          tinynv_last_error());
    CHECK(k.n == 8, "a clocked release is %u dwords; a plain one is 8 (6 of semaphore, 2 of interrupt)", k.n);
    CHECK(words[5] & (1u << 20), "a clocked release does not wait for idle, so it does not mean the work is done");
    CHECK(words[5] & (1u << 25), "a clocked release carries no clock, which is the only reason it exists");
  }
  if (!fails) printf("  timestamps: the start one does not wait for idle, the end one does, and both carry a clock\n");

  // Inline-to-memory, which no recording contains. The replay cannot check this path, so everything the card would
  // otherwise tell us has to be asserted here: the header kinds, the register order, the data, and the size the
  // caller is told to reserve.
  {
    static const uint8_t payload[16] = {0xde, 0xad, 0xbe, 0xef, 1, 2, 3, 4, 0x11, 0x22, 0x33, 0x44, 9, 9, 9, 9};
    uint32_t w[64];
    tinynv_cmdbuf_t c2 = {.words = w, .n = 0, .cap = 64};
    CHECK(!tinynv_cmd_inline_upload(&c2, 0x700000000ull, payload, sizeof(payload)),
          "building an inline upload failed: %s", tinynv_last_error());
    CHECK(c2.n == TINYNV_INLINE_DWORDS(sizeof(payload)),
          "an inline upload of %zu bytes is %u dwords but callers are told to reserve %u - a caller that believes the "
          "macro overruns its batch", sizeof(payload), c2.n, TINYNV_INLINE_DWORDS(sizeof(payload)));
    // The four registers are consecutive, so one INCREMENTING header carries all four: length, one line, then the
    // address high half before the low. Getting that order wrong writes the payload to an address off by 2^32.
    CHECK((w[0] >> 29) == 1, "the register header is not an incrementing method");
    CHECK(w[1] == sizeof(payload) && w[2] == 1, "line length and count are %u/%u, not %zu/1", w[1], w[2],
          sizeof(payload));
    CHECK(w[3] == 7u && w[4] == 0u, "the destination encoded as %#x:%#x rather than high half first", w[3], w[4]);
    // And the data header must be NON-incrementing: LOAD_INLINE_DATA is a fifo at one address, and an incrementing
    // header would walk forward and scatter the payload across the methods that follow it.
    uint32_t dh = w[7];
    CHECK((dh >> 29) == 3, "the inline data header is method kind %u, not non-incrementing (3) - the payload would be "
                           "written to registers past LOAD_INLINE_DATA instead of to memory", dh >> 29);
    CHECK(((dh >> 16) & 0x1fffu) == sizeof(payload) / 4, "the data header carries %u dwords, not %zu",
          (dh >> 16) & 0x1fffu, sizeof(payload) / 4);
    CHECK(!memcmp(&w[8], payload, sizeof(payload)), "the payload is not the bytes that were handed over");

    // And what it refuses. Each of these is a request that cannot be expressed, not a policy.
    tinynv_cmdbuf_t c3 = {.words = w, .n = 0, .cap = 64};
    CHECK(tinynv_cmd_inline_upload(&c3, 0x700000000ull, payload, 6), "a 6-byte inline upload was accepted");
    CHECK(tinynv_cmd_inline_upload(&c3, 0x700000002ull, payload, 8), "an unaligned destination was accepted");
    CHECK(tinynv_cmd_inline_upload(&c3, 0x700000000ull, payload, 0), "a zero-length inline upload was accepted");
    CHECK(tinynv_cmd_inline_upload(&c3, 0x700000000ull, payload, TINYNV_INLINE_MAX + 4),
          "an upload past TINYNV_INLINE_MAX was accepted, which would overrun the stack buffer it is copied through");
  }
  if (!fails) printf("  inline upload: registers, non-incrementing data header, payload and reserved size all pinned\n");

  if (checks < TINYNV_SUBMIT_CHECKS) {
    printf("  FAIL: %d checks ran but this file has %d CHECK sites - a block was skipped and the run would have "
           "reported success\n", checks, TINYNV_SUBMIT_CHECKS);
    fails++;
  }
  printf(fails ? "%d checks failed\n" : "all %d checks passed\n", fails ? fails : checks);
  return fails ? 1 : 0;
}
